"""initial_schema

Revision ID: 80bdb6473967
Revises: 
Create Date: 2026-06-15 16:31:22.529795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80bdb6473967'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('min_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('pay_grade_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contractor', name='employmenttype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='employeestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pay_grade_id'], ['pay_grades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_table('allowances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('allowance_type', sa.Enum('housing', 'transport', 'meal', 'phone', name='allowancetype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.Enum('monthly', 'annual', name='payfrequency'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bonus_type', sa.Enum('annual', 'spot', 'signing', 'performance', name='bonustype'), nullable=False),
    sa.Column('awarded_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('deduction_type', sa.Enum('health_insurance', 'pension', 'other', name='deductiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_percentage', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('frequency', sa.Enum('monthly', 'annual', name='payfrequency'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equity_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('grant_type', sa.Enum('RSU', 'options', name='granttype'), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('grant_date', sa.Date(), nullable=False),
    sa.Column('vest_start_date', sa.Date(), nullable=False),
    sa.Column('cliff_months', sa.Integer(), nullable=False),
    sa.Column('vest_months', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('pay_frequency', sa.Enum('monthly', 'annual', name='payfrequency'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'hr_manager', 'hr_analyst', 'employee', name='userrole'), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('pf_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('employee_contribution_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('employer_contribution_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('applicable_salary_cap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_from_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pf_rules_country'), 'pf_rules', ['country'], unique=False)
    op.create_table('salary_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxable_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_deducted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_employee_contribution', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_employer_contribution', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_take_home', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.Enum('income_tax', 'social_security', 'other', name='taxruletype'), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rules_country'), 'tax_rules', ['country'], unique=False)
    op.create_table('tax_brackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_rule_id', sa.Integer(), nullable=False),
    sa.Column('min_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tax_rule_id'], ['tax_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_brackets')
    op.drop_index(op.f('ix_tax_rules_country'), table_name='tax_rules')
    op.drop_table('tax_rules')
    op.drop_table('salary_slips')
    op.drop_index(op.f('ix_pf_rules_country'), table_name='pf_rules')
    op.drop_table('pf_rules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('salary_records')
    op.drop_table('equity_grants')
    op.drop_table('deductions')
    op.drop_table('bonuses')
    op.drop_table('allowances')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('pay_grades')
    # ### end Alembic commands ###
